Fix ImportError in Centos CI
This fixes an import error with the newest devstack, which conflicts
with the system FreeIPA installation and results in:
ImportError: cannot import name decorate in dogpile.

Change-Id: I8bade87962f3adacbc26a666ea02fedb74963bfa